### ISSUE TITLE
Posts

### ISSUE THREAD

**Issue by rschwietzke** [kurtsson/jekyll-multiple-languages-plugin#18]
Hi, 

all content of _posts seem to be ignored right now. When moved to _i18n, it copies the data incorrectly with _i18n ind the path name.
- Without localization <code>_site/news/2011-12-02-news-12</code>
- with plugin, the data does not arrive at all.

Expected: <code>_site/en/news/2011-12-02-news-12</code>.

When moved to _i18n (_i18n/en/_posts/news/2011-12-02-news-12.html) it becomes: <code>_site/en/_i18n/en/2011-12-02-news-12</code>. So the languages appears twice, the _18in is copied as well, and the topic subfolder is gone.

Any ideas? Maybe I am just doing it incorrectly.

Thanks,
Rene

**Comment by duanefields** [comment]
Willing to fix this on my fork, but I'm not sure I understand the original intention of this code. Does it expect you to have posts inside _i18n/_posts and _posts on the root? What's the desired effect?

````
    def read_posts(dir)
      if dir == ''
        read_posts("_i18n/#{self.config['lang']}/")
      else
        read_posts_org(dir)
      end
    end
  end
````

@kurtsson care to elaborate?

**Comment by duanefields** [comment]
But yes I see the same issue as @rschwietzke, commenting out the overide makes the post show up at all

**Comment by mingjin** [comment]
I also encountered the same issue that Jekyll posts are not generated as original (https://github.com/jekyll/jekyll/blob/v2.5.3/lib/jekyll/site.rb).

After days of digging, it turned out the alias method in this plugin overrides the behaviour from the original Jekyll site class.

I'd suggest that post internationalisation should not be included in the plugin and changing the default behaviour of the original Jekyll be not a good idea, especially with the 'gems' directive in Jekyll's _config.yml.

**Comment by ctruelson** [comment]
In case users don't want to edit the gem to comment out the `read_posts` block, here's a PR that allows for adding "_posts" to the `exclude_from_localization` block

 https://github.com/screeninteraction/jekyll-multiple-languages-plugin/pull/51

**Comment by shushugah** [comment]
With PR #51 merged, this issue can be closed.
